// generated by xcres
//
// DO NOT EDIT. This file is machine-generated and constantly overwritten.
// See https://github.com/mrackwitz/xcres for more info.
//


#import <Foundation/Foundation.h>

FOUNDATION_EXTERN const struct R {
    struct Icons {
        struct IconsImages {
            /// tab_bar/tabbar_list.png
            __unsafe_unretained NSString *tabBarTabbarList;
            /// tab_bar/tabbar_map.png
            __unsafe_unretained NSString *tabBarTabbarMap;
        } Images;
    } Icons;
    struct Images {
        /// doge.jpeg
        __unsafe_unretained NSString *doge;
    } Images;
    struct MediaAssets {
        struct MediaAssetsData {
            /// aif
            __unsafe_unretained NSString *aif;
        } Data;
        struct MediaAssetsImages {
            /// AppIcon
            __unsafe_unretained NSString *app;
            /// Doge
            __unsafe_unretained NSString *doge;
            /// LaunchImage
            __unsafe_unretained NSString *launch;
        } Images;
    } MediaAssets;
    struct ReuseIdentifiers {
        struct ReuseIdentifiersStuff {
            /// row1
            __unsafe_unretained NSString *row1;
            /// row2
            __unsafe_unretained NSString *row2;
            /// row3
            __unsafe_unretained NSString *row3;
        } Stuff;
    } ReuseIdentifiers;
    struct Sounds {
        /// aif.aiff
        __unsafe_unretained NSString *aif;
    } Sounds;
    struct Storyboards {
        /// Stuff
        __unsafe_unretained NSString *stuff;
    } Storyboards;
    struct Strings {
        /// Bar String
        __unsafe_unretained NSString *bar;
        /// Only in english
        __unsafe_unretained NSString *enExclusive;
        /// Lorem Ipsum
        __unsafe_unretained NSString *example;
        /// Foo String
        __unsafe_unretained NSString *foo;
    } Strings;
} R;
