// generated by xcres
//
// DO NOT EDIT. This file is machine-generated and constantly overwritten.
// See https://github.com/mrackwitz/xcres for more info.
//


#import "R.h"

const struct R R = {
    .Icons = {
        .Images = {
            .tabBarTabbarList = @"tab_bar/tabbar_list.png",
            .tabBarTabbarMap = @"tab_bar/tabbar_map.png",
        },
        .Sounds = {
        },
    },
    .Images = {
        .doge = @"doge.jpeg",
    },
    .MediaAssets = {
        .Data = {
            .aif = @"aif",
        },
        .Images = {
            .app = @"AppIcon",
            .doge = @"Doge",
            .launch = @"LaunchImage",
        },
    },
    .Sounds = {
        .aif = @"aif.aiff",
    },
    .Strings = {
        .bar = @"bar",
        .enExclusive = @"en_exclusive",
        .example = @"example",
        .foo = @"foo",
    },
};
