// generated by xcres
//
// DO NOT EDIT. This file is machine-generated and constantly overwritten.
// See https://github.com/mrackwitz/xcres for more info.
//


#import "R.h"

const struct R R = {
    .Icons = {
        .Images = {
            .tabBarTabbarList = @"tab_bar/tabbar_list.png",
            .tabBarTabbarMap = @"tab_bar/tabbar_map.png",
        },
    },
    .Images = {
        .doge = @"doge.jpeg",
    },
    .MediaAssets = {
        .Data = {
            .aif = @"aif",
        },
        .Images = {
            .app = @"AppIcon",
            .doge = @"Doge",
            .launch = @"LaunchImage",
        },
    },
    .ReuseIdentifiers = {
        .Stuff = {
            .row1 = @"row1",
            .row2 = @"row2",
            .row3 = @"row3",
        },
    },
    .Sounds = {
        .aif = @"aif.aiff",
    },
    .Storyboards = {
        .stuff = @"Stuff",
    },
    .Strings = {
        .bar = @"bar",
        .enExclusive = @"en_exclusive",
        .example = @"example",
        .foo = @"foo",
    },
};
