// generated by xcres
//
// DO NOT EDIT. This file is machine-generated and constantly overwritten.
// See https://github.com/mrackwitz/xcres for more info.
//


#import "R.h"

const struct R R = {
    .Icons = {
        .Images = {
            .tabBarTabbarList = @"tab_bar/tabbar_list.png",
            .tabBarTabbarMap = @"tab_bar/tabbar_map.png",
        },
    },
    .Images = {
        .doge = @"doge.jpeg",
    },
    .MediaAssets = {
        .Data = {
            .aif = @"aif",
        },
        .Images = {
            .app = @"AppIcon",
            .doge = @"Doge",
            .launch = @"LaunchImage",
        },
    },
    .RestorationIdentifiers = {
        .Stuff = {
            .restoreTable = @"restoreTable",
            .table2 = @"table2",
        },
    },
    .ReuseIdentifiers = {
        .Stuff = {
            .collection1 = @"collection1",
            .collection2 = @"collection2",
            .row1 = @"row1",
            .row2 = @"row2",
            .row3 = @"row3",
            .table2 = @"table2",
        },
    },
    .SegueIdentifiers = {
        .Stuff = {
            .testSegue = @"testSegue",
        },
    },
    .Sounds = {
        .aif = @"aif.aiff",
    },
    .StoryboardIdentifiers = {
        .Stuff = {
            .col = @"col",
            .nav = @"nav",
            .split = @"split",
            .tab = @"tab",
            .table = @"table",
            .table2 = @"table2",
            .view = @"view",
        },
    },
    .Storyboards = {
        .stuff = @"Stuff",
    },
    .Strings = {
        .bar = @"bar",
        .enExclusive = @"en_exclusive",
        .example = @"example",
        .foo = @"foo",
    },
};
