// generated by xcres
//
// DO NOT EDIT. This file is machine-generated and constantly overwritten.
// See https://github.com/mrackwitz/xcres for more info.
//


#import "R.h"

const struct R R = {
    .ImagesAssets = {
        .Data = {
        },
        .Images = {
            .app = @"AppIcon",
            .launch = @"LaunchImage",
        },
    },
    .Strings = {
    },
};
